networks:
  ticklerio:

services:

  # nginx main server
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/var/www
      - ./logs:/var/log/nginx
      - ./config/ssls:/etc/nginx/ssls
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
    networks:
      - ticklerio

  # nginx feature tests server
  nginx-feature-tests-service:
    image: nginx:stable-alpine
    container_name: nginx-feature-tests-container
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www
      - ./logs:/var/log/nginx
      - ./config/nginx/nginx-feature-tests.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-service
    networks:
      - ticklerio

  # php
  php-service:
    build: 
      context: .
      dockerfile: ./config/php/Dockerfile
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www
#      - ./config/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - ticklerio

  # node
  node-service:
    build:
      context: .
      dockerfile: ./config/node/Dockerfile
      args:
        - "UID=${UID:-1000}"
        - "GID=${GID:-1000}"
    container_name: node-container
    volumes:
      - ./app:/code
    networks:
      - ticklerio
