<?php

namespace Tests;

use GuzzleHttp\Client;
use PHPUnit\Framework\TestCase;
use Phinx\Config\Config;
use Phinx\Migration\Manager;
use Symfony\Component\Console\Input\StringInput;
use Symfony\Component\Console\Output\NullOutput;

class FeatureTestCase extends TestCase
{
    public Client $http;
    public Manager $phinxManager;

    public function __construct(string $name)
    {
        parent::__construct($name);

        $phinxConfig = require __DIR__ . '/../phinx.php';
        $config = new Config($phinxConfig);
        $this->phinxManager = new Manager($config, new StringInput(' '), new NullOutput());
    }

    protected function setUp(): void
    {
        parent::setUp();

        $this->http = new Client([
            'base_uri' => $_ENV['BASE_URL']
        ]);

        $this->phinxManager->migrate('testing');
        $this->phinxManager->seed('testing');
    }

    protected function tearDown(): void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub

        $this->phinxManager->rollback('testing', 0); // reset
    }
}
