name: "CI"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # important!

      # we may use whatever way to install phpcs, just specify the path on the next step
      # however, curl seems to be the fastest
      - name: Install PHP_CodeSniffer
        run: |
          curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
          php phpcs.phar --version

      - name: Find Modified (Non-Deleted) PHP Files in app/src and app/database
        run: |
          echo "MODIFIED_FILES=$(git diff --diff-filter=d --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^(app/src|app/database)/.*\.php$' | xargs)" >> $GITHUB_ENV

      - name: Run PHP_CodeSniffer
        if: env.MODIFIED_FILES != ''
        run: |
          php phpcs.phar --standard=app/phpcs.xml ${{ env.MODIFIED_FILES }}

  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - uses: actions/checkout@v3

      - name: Copy .env
        run: php -r "copy('app/.env.testing.example', 'app/.env');"

      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
        working-directory: app

      - name: Start PHP server
        run: php -S localhost:8000 -t public &
        working-directory: app

      - name: Execute tests (Unit, Integration, and Feature tests) via PHPUnit
        env:
          BASE_URL: http://localhost:8000
        run: vendor/bin/phpunit
        working-directory: app

  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          working_dir: app

      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          configuration: app/phpstan.neon
